// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDicPpBimq3Mui8mZ6o3gjdWfe8HRymI-Q',
    appId: '1:239331473029:web:6914fec6f299053ff89bec',
    messagingSenderId: '239331473029',
    projectId: 'absen-admin-and-siswa',
    authDomain: 'absen-admin-and-siswa.firebaseapp.com',
    storageBucket: 'absen-admin-and-siswa.appspot.com',
    measurementId: 'G-PEX54XVB5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMpoUrQSwYszyDwykLLrH5fNkEEAyWH4w',
    appId: '1:239331473029:android:4834c21bef449bcaf89bec',
    messagingSenderId: '239331473029',
    projectId: 'absen-admin-and-siswa',
    storageBucket: 'absen-admin-and-siswa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0VNgDYEFdwypqEgobCkdsiErSkEwwX58',
    appId: '1:239331473029:ios:edcc3f2829fb4f95f89bec',
    messagingSenderId: '239331473029',
    projectId: 'absen-admin-and-siswa',
    storageBucket: 'absen-admin-and-siswa.appspot.com',
    iosClientId: '239331473029-qojikjlht44grndvlqvak1gkf68pvctl.apps.googleusercontent.com',
    iosBundleId: 'com.example.absenSiswa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0VNgDYEFdwypqEgobCkdsiErSkEwwX58',
    appId: '1:239331473029:ios:edcc3f2829fb4f95f89bec',
    messagingSenderId: '239331473029',
    projectId: 'absen-admin-and-siswa',
    storageBucket: 'absen-admin-and-siswa.appspot.com',
    iosClientId: '239331473029-qojikjlht44grndvlqvak1gkf68pvctl.apps.googleusercontent.com',
    iosBundleId: 'com.example.absenSiswa',
  );
}
